cards = [
  {
    "name": "Winter, Cynical Opportunist",
    "manacost": {
      "red": 0,
      "blue": 0,
      "green": 1,
      "black": 1,
      "white": 0,
      "colorless": 2,
    },
    "type": "Legendary Creature - Human Warlock",
    "power": 2,
    "toughness": 5,
  },
  {
    "name": "Rendmaw, Creaking Nest",
    "manacost": {
      "red": 0,
      "blue": 0,
      "green": 1,
      "black": 1,
      "white": 0,
      "colorless": 3,
    },
    "type": "Legendary Artifact Creature - Scarecrow",
    "power": 5,
    "toughness": 5,
  },
  {
    "name": "Professor Onyx",
    "manacost": {
      "red": 0,
      "blue": 0,
      "green": 0,
      "black": 2,
      "white": 0,
      "colorless": 4,
    },
    "type": "Legendary Planeswalker - Liliana",
    "loyalty": 5,
  },
  {
    "name": "Convert to Slime",
    "manacost": {
      "red": 0,
      "blue": 0,
      "green": 1,
      "black": 1,
      "white": 0,
      "colorless": 3,
    },
    "type": "Sorcery",
  },
  {
    "name": "Sakura-Tribe Elder",
    "manacost": {
      "red": 0,
      "blue": 0,
      "green": 1,
      "black": 1,
      "white": 0,
      "colorless": 3,
    },
    "type": "Creature - Snake Shaman",
    "power": 1,
    "toughness": 1,
  },
]